{% set name = "zipfly" %}
{% set version = "6.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zipfly-{{ version }}.tar.gz
  sha256: 93c56943dca4bf8a1d7de48a15ca9fa8310ade638f2e2493695853a48448efc0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - zipfly
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/buzonIO/zipfly
  summary: A zip archive generator
  license: MIT
  # A pull requests was made upstream to package in LICENSE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
